### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by sujanme25** [deshankha98/lstm-bootstrapping#1]
ci_lowerbound[0,:]=testset_array_sorted[24,:] 
ci_upperbound[0,:]=testset_array_sorted[974,:]

Can't understand where these 24 and 974 came from.

**Comment by deshankha98** [comment]
thats to select non parametric way of choosing confidence interval (CI) upper and lower limit. its 95% CI so 2.5 percentile limit from left and right tail. 1000 samples so  (2.5/100) * 1000 = 25.
25th index from left tail = 24 
and 975th index from right tail = 974

**Comment by sujanme25** [comment]
Thank you but I have a sample of 3506 so the 25th index from the left tail will be 86 and the 3506th index from right tail is 3505. When I did this the dimension mismatch occurs.

**Comment by deshankha98** [comment]
Hey so the way I understand it u have a sample of 3506 no of observations so u can take observation[86, :] & observation[3416, :] as the  lower and upper CI limits.
